Name: "xvm";                       Description: {cm:CompXVM};                 Types: full;                          ExtraDiskSpaceRequired: 7433112
Name: "xvm\clanicons";             Description: {cm:CompXVMClanIcons};        Types: full
Name: "xvm\clanicons\eu";          Description: {cm:CompXVMClanIconsEU};      Types: full;        Flags: exclusive; ExtraDiskSpaceRequired: 147249635
Name: "xvm\clanicons\kr";          Description: {cm:CompXVMClanIconsKR};                          Flags: exclusive; ExtraDiskSpaceRequired: 5461290
Name: "xvm\clanicons\na";          Description: {cm:CompXVMClanIconsNA};                          Flags: exclusive; ExtraDiskSpaceRequired: 50452481
Name: "xvm\clanicons\sg";          Description: {cm:CompXVMClanIconsSG};                          Flags: exclusive; ExtraDiskSpaceRequired: 10191484
Name: "xvm\clanicons\ru";          Description: {cm:CompXVMClanIconsRU};                          Flags: exclusive; ExtraDiskSpaceRequired: 459201364
Name: "hangar";                    Description: {cm:CompHangar};              Types: full custom; Flags: fixed
; Name: "hangar\clock";              Description: {cm:CompClock};               Types: full
Name: "hangar\vtechtree";          Description: {cm:CompVertTechTree};        Types: full;                          ExtraDiskSpaceRequired: 556976
Name: "hangar\vtechtree\btn";      Description: {cm:CompVertTechTreeBtn};     Types: full custom; Flags: fixed
Name: "hangar\vtechtree\btn\ngcx"; Description: {cm:CompVertTechTreeBtnNgcx}; Types: full;        Flags: exclusive
Name: "hangar\vtechtree\btn\ngc";  Description: {cm:CompVertTechTreeBtnNgc};                      Flags: exclusive
Name: "hangar\vtechtree\btn\ngx";  Description: {cm:CompVertTechTreeBtnNgx};                      Flags: exclusive
Name: "hangar\vtechtree\btn\ng";   Description: {cm:CompVertTechTreeBtnNg};                       Flags: exclusive
Name: "hangar\vtechtree\btn\ogcx"; Description: {cm:CompVertTechTreeBtnOgcx};                     Flags: exclusive
Name: "hangar\vtechtree\btn\ogc";  Description: {cm:CompVertTechTreeBtnOgc};                      Flags: exclusive
Name: "hangar\vtechtree\btn\ogx";  Description: {cm:CompVertTechTreeBtnOgx};                      Flags: exclusive
Name: "hangar\vtechtree\btn\og";   Description: {cm:CompVertTechTreeBtnOg};                       Flags: exclusive
Name: "hangar\vtechtree\lyt";      Description: {cm:CompVertTechTreeLyt};     Types: full custom; Flags: fixed
Name: "hangar\vtechtree\lyt\btw";  Description: {cm:CompVertTechTreeLytBtw};  Types: full;        Flags: exclusive
Name: "hangar\vtechtree\lyt\btm";  Description: {cm:CompVertTechTreeLytBtm};                      Flags: exclusive
Name: "hangar\vtechtree\lyt\btd";  Description: {cm:CompVertTechTreeLytBtd};                      Flags: exclusive
Name: "hangar\vtechtree\lyt\btr";  Description: {cm:CompVertTechTreeLytBtr};                      Flags: exclusive
Name: "hangar\vtechtree\lyt\btt";  Description: {cm:CompVertTechTreeLytBtt};                      Flags: exclusive
Name: "hangar\autotelescope";      Description: {cm:CompAutoTelescope};       Types: full;                          ExtraDiskSpaceRequired: 87
Name: "hangar\carousel";           Description: {cm:CompCarousel};            Types: full;                          ExtraDiskSpaceRequired: 379931
Name: "hangar\carousel\carousel2"; Description: {cm:CompCarousel2Row};        Types: full;        Flags: exclusive
Name: "hangar\carousel\carousel3"; Description: {cm:CompCarousel3Row};                            Flags: exclusive
; Name: "hangar\skins";              Description: {cm:CompHangarSkins};         Types: full
; Name: "hangar\skins\tech";         Description: {cm:CompHangarSkinTech};      Types: full;        Flags: exclusive
; Name: "hangar\skins\desert";       Description: {cm:CompHangarSkinDesert};                        Flags: exclusive
; Name: "hangar\skins\livesky";      Description: {cm:CompHangarSkinLiveSky};                       Flags: exclusive
Name: "hangar\skins\carousel";     Description: {cm:CompHangarSkinCarousel};                      Flags: exclusive
Name: "minimap";                   Description: {cm:CompMinimap};             Types: full custom; Flags: fixed
Name: "minimap\hd";                Description: {cm:CompMinimapHD};           Types: full;                          ExtraDiskSpaceRequired: 25064311
; Name: "minimap\tanksview";         Description: {cm:CompMinimapTanksView};    Types: full
Name: "audio";                     Description: {cm:CompAudio};               Types: full custom; Flags: fixed
Name: "audio\gfengines";           Description: {cm:CompAudioGFEngines};      Types: full
Name: "audio\gfguns";              Description: {cm:CompAudioGFGuns};         Types: full
; Name: "gfx";                       Description: {cm:CompGFX};                 Types: full custom; Flags: fixed
